testPractice/Pirates/Pirates/Controllers/PirateController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Pirates.Models;
using PagedList;

namespace Pirates.Controllers
{
    public class PirateController : Controller
    {
        private PirateContext db = new PirateContext();

        // GET: Pirate
        public ActionResult Index(int? page)
        {
                if (page == null)
                    page = 1;

                int pageSize = 3;
                int pageNumber = (page ?? 1);
                var pirates = db.Pirates.ToList();

            return View(pirates.ToPagedList(pageNumber, pageSize));
        }

        // GET: Pirate/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pirate pirate = db.Pirates.Find(id);
            if (pirate == null)
            {
                return HttpNotFound();
            }
            return View(pirate);
        }

        // GET: Pirate/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pirate/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Date")] Pirate pirate)
        {
            if (ModelState.IsValid)
            {
                db.Pirates.Add(pirate);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pirate);
        }

        // GET: Pirate/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pirate pirate = db.Pirates.Find(id);
            if (pirate == null)
            {
                return HttpNotFound();
            }
            return View(pirate);
        }

        // POST: Pirate/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Date")] Pirate pirate)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pirate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pirate);
        }

        // GET: Pirate/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pirate pirate = db.Pirates.Find(id);
            if (pirate == null)
            {
                return HttpNotFound();
            }
            return View(pirate);
        }

        // POST: Pirate/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pirate pirate = db.Pirates.Find(id);
            db.Pirates.Remove(pirate);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

testPractice/Pirates/Pirates/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pirates R Us</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/styles.css" rel="stylesheet" type="text/css"/>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/script.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pirates R Us", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Pirates", "Index", "Pirate", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Ships", "Ships", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Crews", "Crews", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Booty", "CrewGroup", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Pirates Local</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

testPractice/Pirates/Pirates/Views/Shared/_LayoutClient.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <title>@ViewBag.Title</title>

        @* Select your style framework*@
        @*
        @Styles.Render("~/Content/css_bootstrap")
        @Styles.Render("~/Content/css_jqueryUI")
        @Styles.Render("~/Content/css_jmobile")
        *@
        
         @*Contains jquery, all js needed for validation and the main globalize file*@
        @Scripts.Render("~/bundles/basics")

        @* Adds a globalization script specific to the culture selected on the server*@
        @Html.GlobalizationScript("~/Scripts/globalize/cultures/")

        @* Select your style framework*@
        @*
        @Scripts.Render("~/bundles/bootstrap_ext")
        @Scripts.Render("~/bundles/jqueryUIGlob")
        @Scripts.Render("~/bundles/jmobile")
        *@

	@* Preventing jquery-ui-i18n.js from unefficiently setting, one after the other, all cultures    *@
    @* use only with jquery ui *@
    @*
	<script type='text/javascript' >
            $.datepicker.oldSetDefaults = $.datepicker.setDefaults;
            $.datepicker.setDefaults=function(){};
    </script>
    *@
    
    @Scripts.Render("~/bundles/ko")

    @Scripts.Render("~/bundles/mvcct")

    @Scripts.Render("~/bundles/mvcctclient")
    
 
        
    
    @RenderSection("Header", false)

    @* Jquery UI datepicker culture selection. For other style frameworks, please add "@ifs" on the current thread culture to add the right Datepicker globalization script *@
    @*
        <script type='text/javascript' >
        jQuery(function ($) {
            $.datepicker.setDefaults = $.datepicker.oldSetDefaults;
            var jsCulture = $.datepicker.regional["@Culture"] || $.datepicker.regional["@Culture.Substring(0, 2)"];
            if (jsCulture) {
                $.datepicker.setDefaults(jsCulture);
                
            }
        });
     </script>
    *@
     
    <script type='text/javascript' >
        $.validator.setDefaults({
            ignore: ""
        });

    </script>


    </head>

    <body   >

        @RenderBody()
        @RenderSection("Scripts", required: false)
    </body>
</html>

testPractice/Pirates/Pirates/Views/Shared/_LayoutServer.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <title>@ViewBag.Title</title>

        @* Select your style framework*@
        @*
        @Styles.Render("~/Content/css_bootstrap")
        @Styles.Render("~/Content/css_jqueryUI")
        @Styles.Render("~/Content/css_jmobile")
        *@
        
         @*Contains jquery, all js needed for validation and the main globalize file*@
        @Scripts.Render("~/bundles/basics")

        @* Adds a globalization script specific to the culture selected on the server*@
        @Html.GlobalizationScript("~/Scripts/globalize/cultures/")

        @* Select your style framework*@
        @*
        @Scripts.Render("~/bundles/bootstrap_ext")
        @Scripts.Render("~/bundles/jqueryUIGlob")
        @Scripts.Render("~/bundles/jmobile")
        *@

	@* Preventing jquery-ui-i18n.js from unefficiently setting, one after the other, all cultures    *@
    @* use only with jquery ui *@
    @*
	<script type='text/javascript' >
            $.datepicker.oldSetDefaults = $.datepicker.setDefaults;
            $.datepicker.setDefaults=function(){};
    </script>
    *@

    @Scripts.Render("~/bundles/mvcct")
    
 
        
    
    @RenderSection("Header", false)

    @* Jquery UI datepicker culture selection. For other style frameworks, please add "@ifs" on the current thread culture to add the right Datepicker globalization script *@
    @*
        <script type='text/javascript' >
        jQuery(function ($) {
            $.datepicker.setDefaults = $.datepicker.oldSetDefaults;
            var jsCulture = $.datepicker.regional["@Culture"] || $.datepicker.regional["@Culture.Substring(0, 2)"];
            if (jsCulture) {
                $.datepicker.setDefaults(jsCulture);
                
            }
        });
     </script>
    *@
     
    <script type='text/javascript' >
        $.validator.setDefaults({
            ignore: ""
        });
       
    </script>


    </head>

    <body   >

        @RenderBody()
        @RenderSection("Scripts", required: false)
    </body>
</html>