HW5/ChangeMajor/ChangeMajor/Models/Student.cs
namespace ChangeMajor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Student
    {
        /// <summary>
        /// Primary Key in Table
        /// </summary>
        public int ID { get; set; }

        /// <summary>
        /// Student First Name
        /// </summary>
        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }

        /// <summary>
        /// Student Last Name
        /// </summary>
        [Required]
        [StringLength(50)]
        public string LastName { get; set; }

        /// <summary>
        /// Request Date
        /// </summary>
        public DateTime Date { get; set; }

        /// <summary>
        /// Student Phone Number
        /// </summary>
        [StringLength(15)]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Student Email Address
        /// </summary>
        [Required]
        [StringLength(50)]
        public string Email { get; set; }

        /// <summary>
        /// Student's Entry Catalog Year
        /// </summary>
        public int CatalogYear { get; set; }

        /// <summary>
        /// Students V#
        /// </summary>
        [Required]
        [StringLength(11)]
        public string VNumber { get; set; }

        /// <summary>
        /// Students current or requested major
        /// </summary>
        [Required]
        [StringLength(50)]
        public string Major { get; set; }

        /// <summary>
        /// Students current or requested minor
        /// </summary>
        [Required]
        [StringLength(50)]
        public string Minor { get; set; }

        /// <summary>
        /// Students Current or request advisor
        /// </summary>
        [Required]
        [StringLength(50)]
        public string Advisor { get; set; }
    }
}

HW5/ChangeMajor/ChangeMajor/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChangeMajor.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        /// <summary>
        /// Opens the home page
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
    }
}

HW5/ChangeMajor/ChangeMajor/Controllers/StudentController.cs
using ChangeMajor.DAL;
using ChangeMajor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChangeMajor.Controllers
{
    public class StudentController : Controller
    {
        private StudentContext db = new StudentContext();

        /// <summary>
        /// Get the list of all student requests
        /// </summary>
        /// <returns>returns a view of student requests:  ReviewReqs</returns>

        public ActionResult ReviewReqs()
        {
            return View(db.Students.ToList());
        }

        /// <summary>
        /// 
        /// Get the Change Request View
        /// </summary>
        /// <returns>ChangeReq View</returns>
        [HttpGet]
        public ActionResult ChangeReq()
        {
            return View();
        }

        /// <summary>
        /// Takes the info from the form and saves it to the DB redirects to ReviewReq list page
        /// </summary>
        /// <param name="student"></param>
        /// <returns>ReviewReq View</returns>
        [HttpPost]
        public ActionResult ChangeReq(Student student)
        {
            if (ModelState.IsValid)
            {
                db.Students.Add(student);
                db.SaveChanges();
                return RedirectToAction("ReviewReqs");
            }
            return View(student);
        }
    }
}

HW5/ChangeMajor/ChangeMajor/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CS460-HW5</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="styelsheet" />
    <link rel="stylesheet" type="text/css" href="~/Content/Styles.css" />
</head>
<body>
    <div class="jumbotron text-center">
        <h1>Change Major / Minor / Advisor </h1>
        <h4>HW5</h4>
    </div>
    <div class="container">
        <div class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <ul class="nav navbar-nav text-center">
                        <!--use actionlink to create links to other pages in the menu-->
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Change Request", "ChangeReq", "Student")</li>
                        <li>@Html.ActionLink("Review Requests", "ReviewReqs", "Student")</li>
                    </ul>
                </div>
            </div>
        </div>
        <p>Welcome to the home page!</p>
        <p>Select an action from the menu to proceed.</p>
    </div>

</body>
</html>

HW5/ChangeMajor/ChangeMajor/Views/Student/ChangeReq.cshtml
@model ChangeMajor.Models.Student

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Student Change Request</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="styelsheet" />
    <link rel="stylesheet" type="text/css" href="~/Content/Styles.css" />
</head>
<body>
    <div class="jumbotron text-center">
        <h1>Change Major / Minor / Advisor </h1>
        <h4>HW5</h4>
    </div>
    <div class="container">
        <div class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <ul class="nav navbar-nav text-center">
                        <!--use actionlink to create links to other pages in the menu-->
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Change Request", "ChangeReq", "Student")</li>
                        <li>@Html.ActionLink("Review Requests", "ReviewReqs", "Student")</li>
                    </ul>
                </div>
            </div>
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Student - Change Form</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CatalogYear, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CatalogYear, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CatalogYear, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.VNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.VNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.VNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Major, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Major, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Major, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Minor, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Minor, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Minor, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Advisor, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Advisor, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Advisor, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

    </div>
</body>
</html>

HW5/ChangeMajor/ChangeMajor/Views/Student/ReviewReqs.cshtml
@model IEnumerable<ChangeMajor.Models.Student>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Review Change Requests</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="styelsheet" />
    <link rel="stylesheet" type="text/css" href="~/Content/Styles.css" />
</head>
<body>
    <div class="jumbotron text-center">
        <h1>Change Major / Minor / Advisor </h1>
        <h4>HW5</h4>
    </div>
    <div class="container">
        <div class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <ul class="nav navbar-nav text-center">
                        <!--use actionlink to create links to other pages in the menu-->
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Change Request", "ChangeReq", "Student")</li>
                        <li>@Html.ActionLink("Review Requests", "ReviewReqs", "Student")</li>
                    </ul>
                </div>
            </div>
        </div>
        <p>
            @Html.ActionLink("Create New", "ChangeReq", "Student")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PhoneNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CatalogYear)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.VNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Major)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Minor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Advisor)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PhoneNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CatalogYear)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Major)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Minor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Advisor)
                    </td>
                </tr>
            }

        </table>
        </div>
</body>
</html>